spring:
  application:
    name: security-service
  datasource:
    url: jdbc:mysql://localhost:3306/jwts
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

server:
  port: 4321

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 36000000 # 10 hour

eureka:
  client:
    serviceUrl:
      defaultZone: http://13.41.179.170:8761/eureka
